pipeline:
  name: template
  identifier: template
  projectIdentifier: Template_testing
  orgIdentifier: cvng
  tags: {}
  stages:
    - stage:
        name: SLO_AS_CODE
        identifier: SLO_AS_CODE
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          git --version  
                          terraform --version
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - qa-automation-cv-chiplay
                  timeout: 10m
                  failureStrategies: []
              - step:
                  type: TerraformPlan
                  name: Terraform Plan_1
                  identifier: TerraformPlan_1
                  spec:
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            gitFetchType: Branch
                            connectorRef: deepak
                            branch: harness
                            folderPath: harness/slo
                      secretManagerRef: harnessSecretManager
                    provisionerIdentifier: SLO_AS_CODE
                    delegateSelectors:
                      - qa-automation-cv-chiplay
                  timeout: 10m
                  failureStrategies: []
              - step:
                  type: TerraformApply
                  name: Terraform Apply_1
                  identifier: TerraformApply_1
                  spec:
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            type: Github
                            spec:
                              gitFetchType: Branch
                              connectorRef: deepak
                              branch: harness
                              folderPath: harness/slo
                    provisionerIdentifier: SLO_AS_CODE
                    delegateSelectors:
                      - qa-automation-cv-chiplay
                  timeout: 10m
                  failureStrategies: []
        tags: {}
